// Generated by Wrangler on Mon Jan 13 2025 15:36:00 GMT-0800 (Pacific Standard Time)
// by running `wrangler types`

interface Env {
	WDEFOIJ_EFOIJ: string;
	JOCVKJWEW: string;
	EFJIOJVMEW: string;
	FWJIO_WFOLIWLF_WFOUIH: string;
	PRIVATE_IMAGES_API_KEY: string;
	IMAGES_API_TOKEN: string;
	ACCOUNT_ID: string;
	ACCOUNT_HASH: string;
}
