// Generated by Wrangler on Sun Jan 12 2025 08:58:38 GMT-0800 (Pacific Standard Time)
// by running `wrangler types`

interface Env {
	WDEFOIJ_EFOIJ: string;
	JOCVKJWEW: string;
	EFJIOJVMEW: string;
	FWJIO_WFOLIWLF_WFOUIH: string;
}
